# LIBRARIES

In [ ]:
import numpy as np
import os

In [2]:
import importlib
import New_data_prep as dp

importlib.reload(dp)

In [3]:
help(dp.prepare_source_target_datasets)

Help on function prepare_source_target_datasets in module New_data_prep:

prepare_source_target_datasets(path_source: str, path_target: str)
    # final data preparation function

# FIRST DATA PREPARATION

In [78]:
path_to_csvs = "../data/raw/source_domain/"
path_to_csvs_target = "../data/raw/target_domain/"
node_types = ["LIGHT", "MID", "HEAVY"]

In [79]:
result = dp.prepare_source_target_datasets(path_to_csvs, path_to_csvs_target)

/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:45: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, *dataframes], axis=0, ignore_index=True)
/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:56: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.loc[:, col] = X.loc[:, col].fillna(0)

cpu_usage_function_shasum
23887
ram_usage_function_shasum
23430
medium_latency_function_shasum
23610
cpu_usage_function_curl
14017
ram_usage_function_curl
13650
medium_latency_function_curl
13920
cpu_usage_function_eat_memory
4571
ram_usage_function_eat_memory
4501
medium_latency_function_eat_memory
4564
cpu_usage_node
32741
ram_usage_node
32385
ram_usage_node_percentage
32127
ram_usage_node_perc_theor
32385
overloaded_node
overloaded_node
0.0    89169
1.0     9563
Name: count, dtype: int64
cpu_usage_function_nmap
7319
ram_usage_function_nmap
7245
medium_latency_function_nmap
7301
cpu_usage_function_env
19397
ram_usage_function_env
18812
medium_latency_function_env
19202
cpu_usage_function_figlet
19900
ram_usage_function_figlet
19762
medium_latency_function_figlet
19790
cpu_usage_function_figlet
16476
ram_usage_function_figlet
16403
medium_latency_function_figlet
16250
cpu_usage_function_shasum
16498
ram_usage_function_shasum
16352
medium_latency_function_shasum
16298
cpu_usage_function_nmap
7290
ram_usage_function_nmap
7192
medium_latency_function_nmap
7256
cpu_usage_node
21955
ram_usage_node
21629
ram_usage_node_percentage
22094
ram_usage_node_perc_theor
21629
overloaded_node
overloaded_node
0    59483
1     8090
Name: count, dtype: int64
cpu_usage_function_env
8297
ram_usage_function_env
8251
medium_latency_function_env
8119
cpu_usage_function_eat_memory
2817
ram_usage_function_eat_memory
2748
medium_latency_function_eat_memory
2756
cpu_usage_function_curl
6781
ram_usage_function_curl
6695
medium_latency_function_curl
6667

In [108]:
result['tasks']

{'Multi_Task_regression': {'features': ['node_type',
   'rate_function_curl',
   'rate_function_eat_memory',
   'rate_function_env',
   'rate_function_figlet',
   'rate_function_nmap',
   'rate_function_shasum'],
  'targets': ['cpu_usage_function_shasum',
   'ram_usage_function_shasum',
   'medium_latency_function_shasum',
   'cpu_usage_function_curl',
   'ram_usage_function_curl',
   'medium_latency_function_curl',
   'cpu_usage_function_eat_memory',
   'ram_usage_function_eat_memory',
   'medium_latency_function_eat_memory',
   'cpu_usage_node',
   'ram_usage_node',
   'ram_usage_node_percentage',
   'ram_usage_node_perc_theor',
   'cpu_usage_function_nmap',
   'ram_usage_function_nmap',
   'medium_latency_function_nmap',
   'cpu_usage_function_env',
   'ram_usage_function_env',
   'medium_latency_function_env',
   'cpu_usage_function_figlet',
   'ram_usage_function_figlet',
   'medium_latency_function_figlet']},
 'Multi_Task_classification': {'features': ['node_type',
   'rate_function_curl',
   'rate_function_eat_memory',
   'rate_function_env',
   'rate_function_figlet',
   'rate_function_nmap',
   'rate_function_shasum'],
  'targets': ['overloaded_node']}}

In [110]:
result['tasks_unified']['Multi_Task']["features"]

['node_type',
 'rate_function_curl',
 'rate_function_eat_memory',
 'rate_function_env',
 'rate_function_figlet',
 'rate_function_nmap',
 'rate_function_shasum']

In [80]:
df_source = result["df_source"]
df_source

,node_type,rate_function_curl,rate_function_eat_memory,rate_function_env,rate_function_figlet,rate_function_nmap,rate_function_shasum,cpu_usage_function_shasum,ram_usage_function_shasum,medium_latency_function_shasum,...,ram_usage_function_nmap,medium_latency_function_nmap,cpu_usage_function_env,ram_usage_function_env,medium_latency_function_env,cpu_usage_function_figlet,ram_usage_function_figlet,medium_latency_function_figlet,overloaded_status,overloaded_ratio
0,2,60.0,0.0,0.0,0.0,0.0,100.0,7.691,4042069.333,37454241.5,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000,0.000000e+00,0,0.0
1,2,60.0,0.0,0.0,0.0,0.0,100.0,7.751,9199274.667,16880204.0,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000,0.000000e+00,0,0.0
2,2,60.0,0.0,0.0,0.0,0.0,100.0,8.378,9214634.667,35575151.0,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000,0.000000e+00,0,0.0
3,2,60.0,10.0,0.0,0.0,0.0,100.0,8.261,1366357.333,76360433.0,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000,0.000000e+00,1,1.0
4,2,60.0,10.0,0.0,0.0,0.0,100.0,7.820,1323008.000,87032021.0,...,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000,0.000000e+00,1,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
98779,0,0.0,0.0,20.0,70.0,70.0,0.0,0.000,0.000,0.0,...,2.022266e+08,1.655140e+10,2.024333,1.616555e+06,1.278133e+07,10.196000,5607879.111,1.611891e+07,0,0.0
98780,0,0.0,0.0,20.0,70.0,70.0,0.0,0.000,0.000,0.0,...,3.036606e+08,1.697898e+10,2.011000,1.553067e+06,1.207876e+07,10.012000,1713152.000,1.596136e+07,0,0.0
98781,0,0.0,0.0,30.0,70.0,70.0,0.0,0.000,0.000,0.0,...,2.909239e+08,1.728170e+10,2.889333,1.520640e+06,1.444850e+07,9.990167,7250379.020,1.522533e+07,0,0.0
98782,0,0.0,0.0,30.0,70.0,70.0,0.0,0.000,0.000,0.0,...,2.953576e+08,1.793603e+10,2.822000,1.727829e+06,1.444850e+07,9.619000,7250379.020,2.362620e+07,0,0.0
98783,0,0.0,0.0,30.0,70.0,70.0,0.0,0.000,0.000,0.0,...,3.123070e+08,1.753096e+10,2.871000,1.567630e+06,1.485590e+07,9.786000,7250379.020,2.041631e+07,0,0.0

# DATA DISTRIBUTION

In [81]:
path_to_networks = "../data/networks"
n = 20
k = 19
seed = 4850
simulations = range(10)
rng = np.random.default_rng(42)
simulations = range(10)
simulation = 0

In [ ]:
# dp.load_network(
#     path_to_networks: str, 
#     n: int, 
#     k: int, 
#     seed: int, 
#     simulation: int, 
#     rng: np.random.Generator, 
#     node_types: list = None,
#     functions: list = None,
#     n_functions_per_node: int = None
#   )

In [ ]:
# dp.build_nodes_dataframe(
#     data_x: pd.DataFrame, data_y: pd.DataFrame, towers: pd.DataFrame
#   )

In [ ]:
# result = prepare_source_target_datasets(path_to_csvs_source,
#         path_to_csvs_target
#     )

In [82]:
data_x = result["feature_dataset_source"]["Multi_Task"]
data_y = result["target_dataset_source"]["Multi_Task"]

In [104]:
print(result["feature_dataset_source"].keys())

dict_keys(['Multi_Task'])

In [105]:
print(result["target_dataset_source"].keys())

dict_keys(['Multi_Task'])

In [106]:
result["feature_dataset_source"]

{'Multi_Task':        node_type  rate_function_curl  rate_function_eat_memory  \
 0              2                60.0                       0.0
 1              2                60.0                       0.0
 2              2                60.0                       0.0
 3              2                60.0                      10.0
 4              2                60.0                      10.0
 ...          ...                 ...                       ...
 98779          0                 0.0                       0.0
 98780          0                 0.0                       0.0
 98781          0                 0.0                       0.0
 98782          0                 0.0                       0.0
 98783          0                 0.0                       0.0

        rate_function_env  rate_function_figlet  rate_function_nmap  \
 0                    0.0                   0.0                 0.0
 1                    0.0                   0.0                 0.0
 2                    0.0                   0.0                 0.0
 3                    0.0                   0.0                 0.0
 4                    0.0                   0.0                 0.0
 ...                  ...                   ...                 ...
 98779               20.0                  70.0                70.0
 98780               20.0                  70.0                70.0
 98781               30.0                  70.0                70.0
 98782               30.0                  70.0                70.0
 98783               30.0                  70.0                70.0

        rate_function_shasum
 0                     100.0
 1                     100.0
 2                     100.0
 3                     100.0
 4                     100.0
 ...                     ...
 98779                   0.0
 98780                   0.0
 98781                   0.0
 98782                   0.0
 98783                   0.0

 [98732 rows x 7 columns]}

In [83]:
for simulation in simulations:
    print(f"{20*'-'} {simulation} {20*'-'}")

-------------------- 0 --------------------
-------------------- 1 --------------------
-------------------- 2 --------------------
-------------------- 3 --------------------
-------------------- 4 --------------------
-------------------- 5 --------------------
-------------------- 6 --------------------
-------------------- 7 --------------------
-------------------- 8 --------------------
-------------------- 9 --------------------

In [84]:
print(f"porto_{n}n_{k}k/seed{seed}/{simulation}/towers.csv")

porto_20n_19k/seed4850/9/towers.csv

In [85]:
simulation

9

In [87]:
network = dp.load_network(
    path_to_networks,
    n,
    k,
    seed,
    simulation,
    rng,
    node_types
)

In [88]:
network

         lon        lat  node_type
0  -8.609161  41.159592          2
1  -8.619487  41.149209          0
2  -8.601608  41.143799          1
3  -8.611221  41.143112          1
4  -8.589249  41.167831          1
5  -8.612869  41.160690          0
6  -8.609554  41.153412          2
7  -8.628607  41.147307          0
8  -8.604980  41.155120          2
9  -8.598862  41.148453          2
10 -8.598862  41.145859          1
11 -8.609848  41.155472          0
12 -8.611094  41.161612          0
13 -8.615341  41.147232          0
14 -8.627918  41.160393          0
15 -8.611505  41.150291          0
16 -8.587875  41.147232          1
17 -8.604355  41.151352          2
18 -8.611318  41.142476          0
19 -8.626328  41.152725          1

In [90]:
nodes_dataset, test_set = dp.build_nodes_dataframe(
    data_x,
    data_y,
    network
)

In [92]:
print(nodes_dataset.keys())

dict_keys([1, 5, 7, 11, 12, 13, 14, 15, 18, 2, 3, 4, 10, 16, 19, 0, 6, 8, 9, 17])

In [94]:
print(nodes_dataset[5].keys())

dict_keys(['x', 'y'])

In [97]:
nodes_dataset[5]['y']

,cpu_usage_function_shasum,ram_usage_function_shasum,medium_latency_function_shasum,cpu_usage_function_curl,ram_usage_function_curl,medium_latency_function_curl,cpu_usage_function_eat_memory,ram_usage_function_eat_memory,medium_latency_function_eat_memory,cpu_usage_node,...,cpu_usage_function_nmap,ram_usage_function_nmap,medium_latency_function_nmap,cpu_usage_function_env,ram_usage_function_env,medium_latency_function_env,cpu_usage_function_figlet,ram_usage_function_figlet,medium_latency_function_figlet,overloaded_node
81708,5.578333,1.118515e+07,11380890.0,91.912000,5.335732e+07,4.656731e+08,44.589000,5.500553e+07,1.183981e+09,282.217000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81709,5.218000,1.120143e+07,9807629.0,88.173000,1.967218e+06,4.379291e+08,43.236000,5.195281e+07,1.186219e+09,288.568000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81710,5.576000,1.119729e+07,11971438.0,91.516000,1.825451e+06,5.882080e+08,41.998000,5.131002e+07,1.202327e+09,284.304000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81711,6.056000,1.123064e+07,18716905.0,73.437000,1.507912e+08,5.668301e+09,96.724000,8.277505e+07,1.591977e+09,308.972333,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
81712,5.964000,1.120026e+07,18169668.0,73.824000,1.497163e+08,5.832616e+09,93.470000,8.031764e+07,1.572263e+09,318.100000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81517,5.863000,1.550336e+06,17680440.0,19.493000,1.533952e+06,4.098580e+08,248.231000,2.718448e+08,5.535287e+09,360.654000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
81518,5.835000,1.675264e+06,16595165.0,19.739000,1.633166e+06,4.088237e+08,250.623000,2.577382e+08,5.881161e+09,369.414000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
81534,5.644000,1.107223e+07,15658009.0,25.279000,1.894719e+06,4.149690e+08,198.849000,1.941362e+08,3.895496e+09,317.666667,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
81535,5.533000,1.109350e+07,16800969.0,25.628000,1.847296e+06,4.150614e+08,193.955000,2.018137e+08,4.144030e+09,322.650000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
81536,5.413333,1.109009e+07,15909372.0,24.735333,1.830032e+06,4.106533e+08,190.100333,2.043906e+08,4.643391e+09,326.300000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
print(test_set.keys())# 3 perche dataframe costruito per ciascun tipo di nodo

dict_keys([0, 1, 2])

In [100]:
print(test_set[0].keys())

dict_keys(['x', 'y'])

In [101]:
test_set[0]['x']

,node_type,rate_function_curl,rate_function_eat_memory,rate_function_env,rate_function_figlet,rate_function_nmap,rate_function_shasum
98783,0,0.0,0.0,30.0,70.0,70.0,0.0

In [ ]:
network, nodes_dataset, test_set

# SPLIT AND DATA PREPARATION

In [ ]:
def prepare_data(
    node_types: list, 
    path_to_csvs: str, 
    path_to_networks: str, 
    base_output_folder: str,
    n: int, 
    k: int,
    seed: int,
    simulation: int,
    test_perc: float,
    val_perc_on_train: float
  ):
  # prepare output folder
  output_folder = os.path.join(
    base_output_folder, f"{n}n-{k}k", f"seed{seed}", str(simulation)
  )
  if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    # load, filter and scale original data
    print("load, filter and scale original data")
    multi_target_x, multi_target_y, tasks, unified_tasks = load_filter_scale(
      node_types, path_to_csvs
    )
    print("...done")
    # load nodes network
    print("load nodes network")
    rng = np.random.default_rng(seed)
    network = load_network(
      path_to_networks, 
      n, 
      k, 
      seed, 
      simulation, 
      rng,
      node_types = node_types
      # functions = [col for col in multi_target_x if col.startswith('rate')],
      # n_functions_per_node = 3
    )
    print("...done")
    # build nodes dataframes
    print("build nodes dataframes")
    nodes_dataframe, test_set = build_nodes_dataframe(
      multi_target_x, multi_target_y, network
    )
    print("...done")


    # split and save
    print("split and save")
    prepared_nodes_dataset = {}
    train_datasets = []
    val_datasets = []
    test_datasets = []
    for node, data in nodes_dataframe.items():
      group_indices = data["x"].groupby(list(data["x"].columns)).groups
      group_keys = pd.DataFrame(group_indices.keys())
      # -- test
      test_idxs = group_keys.sample(frac = test_perc, random_state = seed)
      test_data = {"x": pd.DataFrame(), "y": pd.DataFrame()}
      for idx in test_idxs.index:
        key = tuple(test_idxs.loc[idx,:])
        test_data["x"] = pd.concat(
          [test_data["x"], data["x"].loc[group_indices[key], :]]
        )
        test_data["y"] = pd.concat(
          [test_data["y"], data["y"].loc[group_indices[key], :]]
        )
      train_val_idxs = group_keys.drop(test_idxs.index)
      # -- validation
      val_idxs = train_val_idxs.sample(
        frac = val_perc_on_train, random_state = seed
      )
      val_data = {"x": pd.DataFrame(), "y": pd.DataFrame()}
      for idx in val_idxs.index:
        key = tuple(val_idxs.loc[idx,:])
        val_data["x"] = pd.concat(
          [val_data["x"], data["x"].loc[group_indices[key], :]]
        )
        val_data["y"] = pd.concat(
          [val_data["y"], data["y"].loc[group_indices[key], :]]
        )
      # -- train
      train_idxs = train_val_idxs.drop(val_idxs.index)
      train_data = {"x": pd.DataFrame(), "y": pd.DataFrame()}
      for idx in train_idxs.index:
        key = tuple(train_idxs.loc[idx,:])
        train_data["x"] = pd.concat(
          [train_data["x"], data["x"].loc[group_indices[key], :]]
        )
        train_data["y"] = pd.concat(
          [train_data["y"], data["y"].loc[group_indices[key], :]]
        )
      train_data["x"].reset_index(inplace = True, drop = True)
      train_data["y"].reset_index(inplace = True, drop = True)
      val_data["x"].reset_index(inplace = True, drop = True)
      val_data["y"].reset_index(inplace = True, drop = True)
      test_data["x"].reset_index(inplace = True, drop = True)
      test_data["y"].reset_index(inplace = True, drop = True)
      # transform
      features = [c for c in train_data["x"].columns if c != "node_type"]
      X_train = transform(train_data["x"], features)
      X_val = transform(val_data["x"], features)
      X_test = transform(test_data["x"], features)
      Y_train = train_data["y"].to_numpy()
      Y_val = val_data["y"].to_numpy()
      Y_test = test_data["y"].to_numpy()
      # save
      prepared_nodes_dataset[node] = (
        X_train, Y_train, X_val, Y_val, X_test, Y_test
      )
      # -- to file
      save_dataset(
        X_train,
        Y_train,
        X_val,
        Y_val,
        X_test,
        Y_test,
        output_folder,
        node
      )
      # prepare datasets to train centralized model
      train_datasets.append((X_train, Y_train))
      val_datasets.append((X_val, Y_val))
      test_datasets.append((X_test, Y_test))
    # aggregate and save centralized dataset
    centralized_train_data = aggregate_datasets(train_datasets)
    centralized_val_data = aggregate_datasets(val_datasets)
    centralized_test_data = aggregate_datasets(test_datasets)
    save_dataset(
      *centralized_train_data,
      *centralized_val_data,
      *centralized_test_data,
      output_folder,
      "centralized"
    )
    # -- save also tasks names
    with open(os.path.join(output_folder, "tasks.json"), "w") as ost:
      ost.write(json.dumps(tasks, indent = 2))
    with open(os.path.join(output_folder, "unified_tasks.json"), "w") as ost:
      ost.write(json.dumps(unified_tasks, indent = 2))
    print("...done")
  else:
    print(f"WARNING: Output folder {output_folder} already exists!")
  return output_folder

# test new function

In [ ]:
def save_xy_split(
    X_train, y_train,
    X_val, y_val,
    X_test, y_test,
    save_dir,
    index=False
):
    """
    Save X and y train/val/test splits separately.

    Files saved:
    - X_train.csv, y_train.csv
    - X_val.csv, y_val.csv
    - X_test.csv, y_test.csv
    """

    os.makedirs(save_dir, exist_ok=True)

    X_train.to_csv(os.path.join(save_dir, "X_train.csv"), index=index)
    y_train.to_csv(os.path.join(save_dir, "y_train.csv"), index=index)

    X_val.to_csv(os.path.join(save_dir, "X_val.csv"), index=index)
    y_val.to_csv(os.path.join(save_dir, "y_val.csv"), index=index)

    X_test.to_csv(os.path.join(save_dir, "X_test.csv"), index=index)
    y_test.to_csv(os.path.join(save_dir, "y_test.csv"), index=index)

In [ ]:
def prepare_single_split_before_training(
    features_dict,
    targets_dict,
    tasks,
    tasks_unified,
    cv_splits_path,
    scaler_path,
    test_size=0.2
):
    all_outputs = {}

    for task_name, task_info in tasks_unified.items():
        printmd(f"# Task: {task_name}")
        printmd("---")

        X = features_dict[task_name]
        y = targets_dict[task_name]

        # =====================================
        # 1. Single split: train_outer / test
        # =====================================
        print(f"Start Train/Test Split: {datetime.datetime.now()}")

        indices = np.arange(len(X))
        train_idx, test_idx = train_test_split(
            indices,
            test_size=test_size,
            stratify=y.values[:, -1].astype(int),
            random_state=42
        )

        X_train_outer, X_test = X.iloc[train_idx], X.iloc[test_idx]
        y_train_outer, y_test = y.iloc[train_idx], y.iloc[test_idx]

        # =====================================
        # 2. Inner split: train / val
        # =====================================
        print(f"Start Train/Val Split: {datetime.datetime.now()}")

        inner_train_idx, inner_val_idx = stratified_group_shuffle_split(
            X_train_outer,
            y_train_outer.values[:, -1].astype(int)
        )

        X_train = X_train_outer.loc[inner_train_idx]
        y_train = y_train_outer.loc[inner_train_idx]
        X_val = X_train_outer.loc[inner_val_idx]
        y_val = y_train_outer.loc[inner_val_idx]

        # =====================================
        # 3. Oversampling only on train
        # =====================================
        print(f"Start Oversampling: {datetime.datetime.now()}")

        df = pd.concat([X_train, y_train], axis=1)
        X_train, y_train, df_augmented, df_balanced = perform_custom_oversampling(
            df,
            task_info["features"],
            task_info["regression_targets"],
            task_info["classification_targets"]
        )

        # =====================================
        # 4. Save raw splits
        # =====================================
        save_xy_split(
            X_train, y_train,
            X_val, y_val,
            X_test, y_test,
            cv_splits_path
        )

        # =====================================
        # 5. Preprocessing
        # =====================================
        print(f"Start Preprocessing: {datetime.datetime.now()}")

        (
            x_train_dict, x_val_dict, x_test_dict, x_scalers,
            y_train_dict, y_val_dict, y_test_dict, y_scalers
        ) = preprocess_fold(
            X_train, X_val, X_test,
            y_train, y_val, y_test,
            tasks_unified,
            scaler_path
        )

        # =====================================
        # 6. Save everything before training
        # =====================================
        all_outputs[task_name] = {
            "X_train_raw": X_train,
            "X_val_raw": X_val,
            "X_test_raw": X_test,
            "y_train_raw": y_train,
            "y_val_raw": y_val,
            "y_test_raw": y_test,
            "df_augmented": df_augmented,
            "df_balanced": df_balanced,
            "x_train_dict": x_train_dict,
            "x_val_dict": x_val_dict,
            "x_test_dict": x_test_dict,
            "y_train_dict": y_train_dict,
            "y_val_dict": y_val_dict,
            "y_test_dict": y_test_dict,
            "x_scalers": x_scalers,
            "y_scalers": y_scalers
        }

    return all_outputs

# TEST DELLA FUNZIONE SEPARATA PER STEP

- adattare prepare data cone le cose che fa kan
- non uso cross validation


obs
- dataset per ogni nodo
- dataset centralizzato
- fare lo split che faceva kan senza cross_validation ma con un seed per lo split (quindi un seed per il network e data distribution e uno per lo split)
- includere le trasformazioni che faceva kan (ex limit identical combinations, transform ecc)


PROBLEMI:
- io ho splittato i dati ma dovrei splittare feature_dataset_source,target_dataset_source,

In [41]:
path_to_csvs = "../data/raw/source_domain/"
path_to_csvs_target = "../data/raw/target_domain/"
node_types = ["LIGHT", "MID", "HEAVY"]
base_output_folder = "../experiments"
path_to_networks = "../data/networks"
n = 20
k = 19
seed = 4850
split_seed=42
simulations = range(10)
rng = np.random.default_rng(42)
simulations = range(10)
simulation = 0

In [29]:
VERSION = 'V1'
PATH_TO_SCALERS =  f'../output/scalers/baselines/{VERSION}/'
PATH_TO_MODELS =  f"../output/system-forecaster-models/baselines/{VERSION}/"
PATH_TO_RESULTS =  f"../output/results/baselines/{VERSION}/"
PATH_TO_TRAINING_LOGS =  f"../output/training_logs/baselines/{VERSION}/"
PATH_TO_AUGMENTED_ROWS =  f"../data/augmented_rows/baselines/{VERSION}/"
PATH_TO_SPLITS =  f"../data/splits/{VERSION}/"
PATH_TO_PLOTS  = f"../output/plots/baselines/{VERSION}/"

In [85]:
features = ['node_type',
 'rate_function_curl',
 'rate_function_eat_memory',
 'rate_function_env',
 'rate_function_figlet',
 'rate_function_nmap',
 'rate_function_shasum']

In [31]:
def save_xy_split(
    X_train, y_train,
    X_val, y_val,
    X_test, y_test,
    save_dir,
    index=False
):
    """
    Save X and y train/val/test splits separately.

    Files saved:
    - X_train.csv, y_train.csv
    - X_val.csv, y_val.csv
    - X_test.csv, y_test.csv
    """

    os.makedirs(save_dir, exist_ok=True)

    X_train.to_csv(os.path.join(save_dir, "X_train.csv"), index=index)
    y_train.to_csv(os.path.join(save_dir, "y_train.csv"), index=index)

    X_val.to_csv(os.path.join(save_dir, "X_val.csv"), index=index)
    y_val.to_csv(os.path.join(save_dir, "y_val.csv"), index=index)

    X_test.to_csv(os.path.join(save_dir, "X_test.csv"), index=index)
    y_test.to_csv(os.path.join(save_dir, "y_test.csv"), index=index)

In [32]:
def get_folds(X, y, n_splits=5, random_state=42):

    # overload is last column
    y_overload = y.values[:, -1].astype(int)

    # group on identical feature vectors
    groups = X.apply(lambda row: tuple(row.values), axis=1)

    skf = StratifiedGroupKFold(
        n_splits=n_splits,
        shuffle=True,
        random_state=random_state
    )

    return skf.split(X.values, y_overload, groups)

In [57]:
def stratified_group_shuffle_split(X, y, groups=None, test_size=0.2, random_state=42):
    """
    Performs a stratified shuffle split on groups.
    Optimized for performance and includes memory cleanup.
    """
    if groups is None:
        # Generate unique hash for each row to represent groups.
        # This is generally faster than X.apply(tuple, axis=1) for DataFrames.
        if not isinstance(X, pd.DataFrame):
            X_df = pd.DataFrame(X)
        else:
            X_df = X
        groups = pd.util.hash_pandas_object(X_df, index=False)
        # Ensure 'groups' is a Series with the correct index for subsequent operations
        groups = pd.Series(groups, index=X.index)

    rng = check_random_state(random_state)

    # 1. group-level table
    df_group_y = pd.DataFrame({"group": groups, "y": y}, index=X.index)
    # Ensure y is numeric for mode calculation or handle non-numeric cases if necessary
    group_labels = df_group_y.groupby("group")["y"].agg(lambda s: s.mode()[0])

    unique_groups = group_labels.index.values
    strat_labels = group_labels.values

    # 2. stratified split on groups
    sss = StratifiedShuffleSplit(
        n_splits=1, test_size=test_size, random_state=random_state
    )
    (train_groups_idx, test_groups_idx) = next(sss.split(unique_groups, strat_labels))

    train_groups = unique_groups[train_groups_idx]
    test_groups = unique_groups[test_groups_idx]

    # 3. map back to row indices using boolean indexing for efficiency
    train_mask = groups.isin(train_groups)
    test_mask = groups.isin(test_groups)

    train_idx = X.index[train_mask].values
    test_idx = X.index[test_mask].values

    # Memory cleanup
    del df_group_y, group_labels, unique_groups, strat_labels, train_mask, test_mask
    if groups is not None and isinstance(groups, pd.Series):
        del groups
    del rng
    gc.collect()

    return train_idx, test_idx

In [79]:
def single_split_preprocessing(
    features_dict,
    targets_dict,
    tasks_unified,
    output_path,
    scaler_path,
    n_splits=5,
    random_state=42
):
    task_name = "Multi_Task"
    task_info = tasks_unified[task_name]

    printmd(f"# Task: {task_name}")
    printmd("---")

    X = features_dict
    y = targets_dict

    # =====================================
    # STESSO SPLIT DELLA CROSS_VALIDATE
    # ma uso solo il primo fold
    # =====================================
    print(f"Start CV Split (single fold only): {datetime.datetime.now()}")
    splits = get_folds(X, y, n_splits=n_splits, random_state=random_state)

    train_idx, test_idx = next(splits)

    # Outer split: train/test
    X_train_outer, X_test = X.iloc[train_idx], X.iloc[test_idx]
    y_train_outer, y_test = y.iloc[train_idx], y.iloc[test_idx]

    # =====================================
    # STESSO SPLIT TRAIN/VAL DELLA CROSS_VALIDATE
    # =====================================
    print(f"Start Train/Val Split: {datetime.datetime.now()}")
    inner_train_idx, inner_val_idx = stratified_group_shuffle_split(
        X_train_outer,
        y_train_outer.values[:, -1].astype(int),
        random_state=random_state
    )

    X_train = X_train_outer.loc[inner_train_idx]
    y_train = y_train_outer.loc[inner_train_idx]
    X_val = X_train_outer.loc[inner_val_idx]
    y_val = y_train_outer.loc[inner_val_idx]

    # =====================================
    # OVERSAMPLING SOLO TRAIN
    # =====================================
    print(f"Start Oversampling: {datetime.datetime.now()}")
    df_train = pd.concat([X_train, y_train], axis=1)

    X_train, y_train, df_augmented, df_balanced = perform_custom_oversampling(
        df_train,
        task_info["features"],
        task_info["regression_targets"],
        task_info["classification_targets"]
    )

    # =====================================
    # SALVA SPLIT RAW
    # =====================================
    save_xy_split(
        X_train, y_train,
        X_val, y_val,
        X_test, y_test,
        output_path
    )

    # =====================================
    # PREPROCESSING
    # =====================================
    print(f"Start Preprocessing: {datetime.datetime.now()}")

    (
        x_train_dict, x_val_dict, x_test_dict, x_scalers,
        y_train_dict, y_val_dict, y_test_dict, y_scalers
    ) = preprocess_fold(
        X_train, X_val, X_test,
        y_train, y_val, y_test,
        tasks_unified,
        scaler_path
    )

    all_outputs = {
        "X_train_raw": X_train,
        "X_val_raw": X_val,
        "X_test_raw": X_test,
        "y_train_raw": y_train,
        "y_val_raw": y_val,
        "y_test_raw": y_test,
        "df_augmented": df_augmented,
        "df_balanced": df_balanced,
        "x_train_dict": x_train_dict,
        "x_val_dict": x_val_dict,
        "x_test_dict": x_test_dict,
        "y_train_dict": y_train_dict,
        "y_val_dict": y_val_dict,
        "y_test_dict": y_test_dict,
        "x_scalers": x_scalers,
        "y_scalers": y_scalers
    }

    return all_outputs

In [14]:
# def prepare_data(
#     node_types: list, 
#     path_to_csvs: str, 
#     path_to_networks: str, 
#     base_output_folder: str,
#     n: int, 
#     k: int,
#     seed: int,
#     simulation: int,
#     test_perc: float,
#     val_perc_on_train: float
#   ):
  # prepare output folder
output_folder = os.path.join(
  base_output_folder, f"{n}n-{k}k", f"seed{seed}", str(simulation)
)
if not os.path.exists(output_folder):
  os.makedirs(output_folder)

In [12]:
output_folder

'../experiments/20n-19k/seed4850/0'

In [ ]:
  #  # load, filter and scale original data
  #   print("load, filter and scale original data")
  #   multi_target_x, multi_target_y, tasks, unified_tasks = load_filter_scale(
  #     node_types, path_to_csvs
  #   )
  #   print("...done")

In [ ]:
  #   multi_target_x, multi_target_y, tasks, unified_tasks = load_filter_scale(
  #     node_types, path_to_csvs
  #   )

In [ ]:
data = dp.prepare_source_target_datasets(path_to_csvs, path_to_csvs_target)
multi_target_x = data["feature_dataset_source"]["Multi_Task"]
multi_target_y = data["target_dataset_source"]["Multi_Task"]
tasks = data["tasks"]
unified_tasks = data["tasks_unified"]

/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:45: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, *dataframes], axis=0, ignore_index=True)
/Users/kingsley/Documents/TESI/GITHUB_TESI/gl-forecasting-edge-performance/src/New_data_prep.py:56: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  X.loc[:, col] = X.loc[:, col].fillna(0)

cpu_usage_function_shasum
23887
ram_usage_function_shasum
23430
medium_latency_function_shasum
23610
cpu_usage_function_curl
14017
ram_usage_function_curl
13650
medium_latency_function_curl
13920
cpu_usage_function_eat_memory
4571
ram_usage_function_eat_memory
4501
medium_latency_function_eat_memory
4564
cpu_usage_node
32741
ram_usage_node
32385
ram_usage_node_percentage
32127
ram_usage_node_perc_theor
32385
overloaded_node
overloaded_node
0.0    89169
1.0     9563
Name: count, dtype: int64
cpu_usage_function_nmap
7319
ram_usage_function_nmap
7245
medium_latency_function_nmap
7301
cpu_usage_function_env
19397
ram_usage_function_env
18812
medium_latency_function_env
19202
cpu_usage_function_figlet
19900
ram_usage_function_figlet
19762
medium_latency_function_figlet
19790
cpu_usage_function_figlet
16476
ram_usage_function_figlet
16403
medium_latency_function_figlet
16250
cpu_usage_function_shasum
16498
ram_usage_function_shasum
16352
medium_latency_function_shasum
16298
cpu_usage_function_nmap
7290
ram_usage_function_nmap
7192
medium_latency_function_nmap
7256
cpu_usage_node
21955
ram_usage_node
21629
ram_usage_node_percentage
22094
ram_usage_node_perc_theor
21629
overloaded_node
overloaded_node
0    59483
1     8090
Name: count, dtype: int64
cpu_usage_function_env
8297
ram_usage_function_env
8251
medium_latency_function_env
8119
cpu_usage_function_eat_memory
2817
ram_usage_function_eat_memory
2748
medium_latency_function_eat_memory
2756
cpu_usage_function_curl
6781
ram_usage_function_curl
6695
medium_latency_function_curl
6667

In [ ]:
# load nodes network
# print("load nodes network")
# rng = np.random.default_rng(seed)
# network = load_network(
#   path_to_networks, 
#   n, 
#   k, 
#   seed, 
#   simulation, 
#   rng,
#   node_types = node_types
#   # functions = [col for col in multi_target_x if col.startswith('rate')],
#   # n_functions_per_node = 3
# )
# print("...done")

In [17]:
rng = np.random.default_rng(seed)
network = dp.load_network(
    path_to_networks,
    n,
    k,
    seed,
    simulation,
    rng,
    node_types
)

In [18]:
network

         lon        lat  node_type
0  -8.609161  41.159592          0
1  -8.619487  41.149209          2
2  -8.601608  41.143799          1
3  -8.611221  41.143112          1
4  -8.589249  41.167831          0
5  -8.612869  41.160690          1
6  -8.609554  41.153412          1
7  -8.628607  41.147307          1
8  -8.604980  41.155120          0
9  -8.598862  41.148453          1
10 -8.598862  41.145859          0
11 -8.609848  41.155472          0
12 -8.611094  41.161612          0
13 -8.615341  41.147232          0
14 -8.627918  41.160393          0
15 -8.611505  41.150291          2
16 -8.587875  41.147232          0
17 -8.604355  41.151352          1
18 -8.611318  41.142476          2
19 -8.626328  41.152725          1

In [22]:
  # build nodes dataframes
print("build nodes dataframes")

nodes_dataframe, test_set = dp.build_nodes_dataframe(
    multi_target_x,
    multi_target_y,
    network
)

print("...done")

build nodes dataframes
...done

In [38]:
nodes_dataframe[5].keys()

dict_keys(['x', 'y'])

In [33]:
for node, data in nodes_dataframe.items():
  print(f"Node {node}:")
#   print(f"  x shape: {data['x'].shape}")
#   print(f"  y shape: {data['y'].shape}")

Node 0:
Node 4:
Node 8:
Node 10:
Node 11:
Node 12:
Node 13:
Node 14:
Node 16:
Node 2:
Node 3:
Node 5:
Node 6:
Node 7:
Node 9:
Node 17:
Node 19:
Node 1:
Node 15:
Node 18:

In [ ]:
# all_results_source, all_training_times_source = cross_validate(feature_dataset_source,target_dataset_source,tasks,tasks_unified,
#                                                              cv_splits_path = PATH_TO_SPLITS+"source/",
#                                                              scaler_path = PATH_TO_SCALERS+"source/",
#                                                               models_path = PATH_TO_MODELS+"source/",
#                                                              logs_path = PATH_TO_TRAINING_LOGS + "source/",
#                                                              results_path = PATH_TO_RESULTS +"source/",
#                                                               plot_path = PATH_TO_PLOTS +"source/",
#                                                              n_splits=5)

In [ ]:
    # features_dict,
    # targets_dict,
    # tasks_unified,
    # output_path,
    # scaler_path,
    # n_splits=5,
    # random_state=42

In [59]:
import pandas as pd
import datetime
from IPython.display import display, HTML
from IPython.display import Markdown, display

def printmd(string):
    display(Markdown(string))

def display_results(results_df):
  for task_name, df in results_df.items():
    printmd(f"# {task_name}")
    printmd("---")
    display(HTML(df.to_html()))

In [89]:
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.utils import check_random_state
from sklearn.model_selection import StratifiedShuffleSplit
import gc
from math import ceil
from sklearn.preprocessing import MinMaxScaler
import joblib
from sklearn.preprocessing import OneHotEncoder
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
print("split and save")
prepared_nodes_dataset = {}
train_datasets = []
val_datasets = []
test_datasets = []
for node, data in nodes_dataframe.items():
  outputs = single_split_preprocessing(data["x"], data["y"],unified_tasks, PATH_TO_SPLITS, PATH_TO_SCALERS,n_splits=5,random_state=split_seed)

In [73]:
unified_tasks['Multi_Task']

{'features': ['node_type',
  'rate_function_curl',
  'rate_function_eat_memory',
  'rate_function_env',
  'rate_function_figlet',
  'rate_function_nmap',
  'rate_function_shasum'],
 'targets': ['cpu_usage_function_shasum',
  'ram_usage_function_shasum',
  'medium_latency_function_shasum',
  'cpu_usage_function_curl',
  'ram_usage_function_curl',
  'medium_latency_function_curl',
  'cpu_usage_function_eat_memory',
  'ram_usage_function_eat_memory',
  'medium_latency_function_eat_memory',
  'cpu_usage_node',
  'ram_usage_node',
  'ram_usage_node_percentage',
  'ram_usage_node_perc_theor',
  'cpu_usage_function_nmap',
  'ram_usage_function_nmap',
  'medium_latency_function_nmap',
  'cpu_usage_function_env',
  'ram_usage_function_env',
  'medium_latency_function_env',
  'cpu_usage_function_figlet',
  'ram_usage_function_figlet',
  'medium_latency_function_figlet',
  'overloaded_node'],
 'regression_targets': ['cpu_usage_function_shasum',
  'ram_usage_function_shasum',
  'medium_latency_function_shasum',
  'cpu_usage_function_curl',
  'ram_usage_function_curl',
  'medium_latency_function_curl',
  'cpu_usage_function_eat_memory',
  'ram_usage_function_eat_memory',
  'medium_latency_function_eat_memory',
  'cpu_usage_node',
  'ram_usage_node',
  'ram_usage_node_percentage',
  'ram_usage_node_perc_theor',
  'cpu_usage_function_nmap',
  'ram_usage_function_nmap',
  'medium_latency_function_nmap',
  'cpu_usage_function_env',
  'ram_usage_function_env',
  'medium_latency_function_env',
  'cpu_usage_function_figlet',
  'ram_usage_function_figlet',
  'medium_latency_function_figlet'],
 'classification_targets': ['overloaded_node']}

In [47]:
print(single_split_preprocessing)

<function single_split_preprocessing at 0x173913880>

In [48]:
import inspect
print(inspect.signature(single_split_preprocessing))

(features_dict, targets_dict, tasks_unified, output_path, scaler_path, n_splits=5, split_seed=42)

In [93]:
outputs.keys()

dict_keys(['X_train_raw', 'X_val_raw', 'X_test_raw', 'y_train_raw', 'y_val_raw', 'y_test_raw', 'df_augmented', 'df_balanced', 'x_train_dict', 'x_val_dict', 'x_test_dict', 'y_train_dict', 'y_val_dict', 'y_test_dict', 'x_scalers', 'y_scalers'])

In [ ]:
# split and save
print("split and save")
prepared_nodes_dataset = {}
train_datasets = []
val_datasets = []
test_datasets = []
for node, data in nodes_dataframe.items():
  outputs = single_split_preprocessing(data["x"], data["y"],unified_tasks, PATH_TO_SPLITS, PATH_TO_SCALERS,n_splits=5,random_state=split_seed)

  X_train = outputs["X_train_raw"].to_numpy()
  Y_train = outputs["y_train_raw"].to_numpy()

  X_val = outputs["X_val_raw"].to_numpy()
  Y_val = outputs["y_val_raw"].to_numpy()

  X_test = outputs["X_test_raw"].to_numpy()
  Y_test = outputs["y_test_raw"].to_numpy()
  # save
  prepared_nodes_dataset[node] = (
    X_train, Y_train, X_val, Y_val, X_test, Y_test
  )

In [97]:
print("split and save")
prepared_nodes_dataset = {}
train_datasets = []
val_datasets = []
test_datasets = []
for node, data in nodes_dataframe.items():
  outputs = single_split_preprocessing(data["x"], data["y"],unified_tasks, PATH_TO_SPLITS, PATH_TO_SCALERS,n_splits=5,random_state=split_seed)

  X_train = outputs["X_train_raw"].to_numpy()
  Y_train = outputs["y_train_raw"].to_numpy()

  X_val = outputs["X_val_raw"].to_numpy()
  Y_val = outputs["y_val_raw"].to_numpy()

  X_test = outputs["X_test_raw"].to_numpy()
  Y_test = outputs["y_test_raw"].to_numpy()
  # save
  prepared_nodes_dataset[node] = (
    X_train, Y_train, X_val, Y_val, X_test, Y_test
  )

  # -- to file
  save_dataset(
    X_train,
    Y_train,
    X_val,
    Y_val,
    X_test,
    Y_test,
    output_folder,
    node
  )
  # prepare datasets to train centralized model
  train_datasets.append((X_train, Y_train))
  val_datasets.append((X_val, Y_val))
  test_datasets.append((X_test, Y_test))
# aggregate and save centralized dataset
centralized_train_data = aggregate_datasets(train_datasets)
centralized_val_data = aggregate_datasets(val_datasets)
centralized_test_data = aggregate_datasets(test_datasets)
save_dataset(
  *centralized_train_data,
  *centralized_val_data,
  *centralized_test_data,
  output_folder,
  "centralized"
)
# -- save also tasks names
with open(os.path.join(output_folder, "tasks.json"), "w") as ost:
  ost.write(json.dumps(tasks, indent = 2))
with open(os.path.join(output_folder, "unified_tasks.json"), "w") as ost:
  ost.write(json.dumps(unified_tasks, indent = 2))
print("...done")
else:
print(f"WARNING: Output folder {output_folder} already exists!")
return output_folder

SyntaxError: invalid syntax (2093856275.py, line 54)

In [ ]:
   # -- to file
      save_dataset(
        X_train,
        Y_train,
        X_val,
        Y_val,
        X_test,
        Y_test,
        output_folder,
        node
      )
      # prepare datasets to train centralized model
      train_datasets.append((X_train, Y_train))
      val_datasets.append((X_val, Y_val))
      test_datasets.append((X_test, Y_test))
    # aggregate and save centralized dataset
    centralized_train_data = aggregate_datasets(train_datasets)
    centralized_val_data = aggregate_datasets(val_datasets)
    centralized_test_data = aggregate_datasets(test_datasets)
    save_dataset(
      *centralized_train_data,
      *centralized_val_data,
      *centralized_test_data,
      output_folder,
      "centralized"
    )
    # -- save also tasks names
    with open(os.path.join(output_folder, "tasks.json"), "w") as ost:
      ost.write(json.dumps(tasks, indent = 2))
    with open(os.path.join(output_folder, "unified_tasks.json"), "w") as ost:
      ost.write(json.dumps(unified_tasks, indent = 2))
    print("...done")
  else:
    print(f"WARNING: Output folder {output_folder} already exists!")
  return output_folder

# final function

In [112]:
from utils.data import save_dataset
from utils.centralized_training import aggregate_datasets
import json

In [113]:
from utils.centralized_training import aggregate_datasets
from utils.data import save_dataset

from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
import matplotlib.pyplot as plt
from typing import Tuple
import seaborn as sns
import pandas as pd
import numpy as np
import joblib
import json
import os

import datetime
from math import ceil
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.utils import check_random_state
from sklearn.model_selection import StratifiedShuffleSplit
import gc
from math import ceil

In [116]:
output_folder = os.path.join(
  base_output_folder, f"{n}n-{k}k", f"seed{seed}", str(simulation)
)
if not os.path.exists(output_folder):
  os.makedirs(output_folder)

  data = dp.prepare_source_target_datasets(path_to_csvs, path_to_csvs_target)
  multi_target_x = data["feature_dataset_source"]["Multi_Task"]
  multi_target_y = data["target_dataset_source"]["Multi_Task"]
  tasks = data["tasks"]
  unified_tasks = data["tasks_unified"]

  print("load nodes network")
  rng = np.random.default_rng(seed)
  network = dp.load_network(
      path_to_networks,
      n,
      k,
      seed,
      simulation,
      rng,
      node_types
  )
  print("...done")

    # build nodes dataframes
  print("build nodes dataframes")

  nodes_dataframe, test_set = dp.build_nodes_dataframe(
      multi_target_x,
      multi_target_y,
      network
  )

  print("...done")

  # split and save
  print("split and save")
  prepared_nodes_dataset = {}
  train_datasets = []
  val_datasets = []
  test_datasets = []
  for node, data in nodes_dataframe.items():
    outputs = single_split_preprocessing(data["x"], data["y"],unified_tasks, PATH_TO_SPLITS, PATH_TO_SCALERS,n_splits=5,random_state=split_seed)

    X_train = outputs["X_train_raw"].to_numpy()
    Y_train = outputs["y_train_raw"].to_numpy()

    X_val = outputs["X_val_raw"].to_numpy()
    Y_val = outputs["y_val_raw"].to_numpy()

    X_test = outputs["X_test_raw"].to_numpy()
    Y_test = outputs["y_test_raw"].to_numpy()
    # save
    prepared_nodes_dataset[node] = (
      X_train, Y_train, X_val, Y_val, X_test, Y_test
    )

    print("split and save")

    # -- to file
    save_dataset(
      X_train,
      Y_train,
      X_val,
      Y_val,
      X_test,
      Y_test,
      output_folder,
      node
    )
    # prepare datasets to train centralized model
    train_datasets.append((X_train, Y_train))
    val_datasets.append((X_val, Y_val))
    test_datasets.append((X_test, Y_test))
    # aggregate and save centralized dataset
  centralized_train_data = aggregate_datasets(train_datasets)
  centralized_val_data = aggregate_datasets(val_datasets)
  centralized_test_data = aggregate_datasets(test_datasets)
  save_dataset(
    *centralized_train_data,
    *centralized_val_data,
    *centralized_test_data,
    output_folder,
    "centralized"
  )
  # -- save also tasks names
  with open(os.path.join(output_folder, "tasks.json"), "w") as ost:
    ost.write(json.dumps(tasks, indent = 2))
  with open(os.path.join(output_folder, "unified_tasks.json"), "w") as ost:
    ost.write(json.dumps(unified_tasks, indent = 2))
  print("...done")
else:
  print(f"WARNING: Output folder {output_folder} already exists!")
#return output_folder

WARNING: Output folder ../experiments/20n-19k/seed4850/0 already exists!

In [106]:
output_folder

'../experiments/20n-19k/seed4850/0'

In [ ]:
def run_simulation_pipeline(
    base_output_folder,
    path_to_csvs,
    path_to_csvs_target,
    path_to_networks,
    PATH_TO_SPLITS,
    PATH_TO_SCALERS,
    n,
    k,
    seed,
    simulation,
    node_types,
    split_seed
):

    # ===============================
    # OUTPUT FOLDER
    # ===============================
    output_folder = os.path.join(
        base_output_folder, f"{n}n-{k}k", f"seed{seed}", str(simulation)
    )

    if os.path.exists(output_folder):
        print(f"WARNING: Output folder {output_folder} already exists!")
        return output_folder

    os.makedirs(output_folder)

    # ===============================
    # LOAD DATA
    # ===============================
    data = dp.prepare_source_target_datasets(path_to_csvs, path_to_csvs_target)

    multi_target_x = data["feature_dataset_source"]["Multi_Task"]
    multi_target_y = data["target_dataset_source"]["Multi_Task"]
    tasks = data["tasks"]
    unified_tasks = data["tasks_unified"]

    # ===============================
    # LOAD NETWORK
    # ===============================
    print("load nodes network")
    rng = np.random.default_rng(seed)

    network = dp.load_network(
        path_to_networks,
        n,
        k,
        seed,
        simulation,
        rng,
        node_types
    )
    print("...done")

    # ===============================
    # BUILD NODE DATASETS
    # ===============================
    print("build nodes dataframes")

    nodes_dataframe, test_set = dp.build_nodes_dataframe(
        multi_target_x,
        multi_target_y,
        network
    )

    print("...done")

    # ===============================
    # SPLIT & SAVE
    # ===============================
    print("split and save")

    prepared_nodes_dataset = {}
    train_datasets = []
    val_datasets = []
    test_datasets = []

    for node, node_data in nodes_dataframe.items():

        print(f"processing node {node}")

        node_split_path = os.path.join(PATH_TO_SPLITS, f"node_{node}")
        node_scaler_path = os.path.join(PATH_TO_SCALERS, f"node_{node}")

        outputs = single_split_preprocessing(
            node_data["x"],
            node_data["y"],
            unified_tasks,
            node_split_path,
            node_scaler_path,
            n_splits=5,
            random_state=split_seed
        )

        X_train = outputs["X_train_raw"].to_numpy()
        Y_train = outputs["y_train_raw"].to_numpy()

        X_val = outputs["X_val_raw"].to_numpy()
        Y_val = outputs["y_val_raw"].to_numpy()

        X_test = outputs["X_test_raw"].to_numpy()
        Y_test = outputs["y_test_raw"].to_numpy()

        # Save in memory
        prepared_nodes_dataset[node] = (
            X_train, Y_train, X_val, Y_val, X_test, Y_test
        )

        # Save per node
        save_dataset(
            X_train,
            Y_train,
            X_val,
            Y_val,
            X_test,
            Y_test,
            output_folder,
            node
        )

        # For centralized dataset
        train_datasets.append((X_train, Y_train))
        val_datasets.append((X_val, Y_val))
        test_datasets.append((X_test, Y_test))

    # ===============================
    # CENTRALIZED DATASET
    # ===============================
    centralized_train_data = aggregate_datasets(train_datasets)
    centralized_val_data = aggregate_datasets(val_datasets)
    centralized_test_data = aggregate_datasets(test_datasets)

    save_dataset(
        *centralized_train_data,
        *centralized_val_data,
        *centralized_test_data,
        output_folder,
        "centralized"
    )

    # ===============================
    # SAVE TASK METADATA
    # ===============================
    with open(os.path.join(output_folder, "tasks.json"), "w") as ost:
        ost.write(json.dumps(tasks, indent=2))

    with open(os.path.join(output_folder, "unified_tasks.json"), "w") as ost:
        ost.write(json.dumps(unified_tasks, indent=2))

    print("...done")

    return output_folder

# funzioni gia in new_data_prep

In [67]:
# perform_custom_oversampling (used in cross_validate) ----------------------------------------------------------------------------------------------------------
def limit_identical_combinations(df, features, target_cols, max_per_combination=1): # used in perform_custom_oversampling
    """
    Limit the dataset to at most `max_per_combination` identical feature combinations.

    Parameters
    ----------
    df : pd.DataFrame
    features : list
        Columns to group by when identifying identical combinations.
    target_cols : list
        Target column names.
    max_per_combination : int
        Maximum allowed identical combinations per group.

    Returns
    -------
    df_limited : pd.DataFrame
        Reduced datasets after limiting duplicates.
    """
    print(f"\n=== Limiting to max {max_per_combination} identical combinations ===")

    # df_combined = pd.concat([X, y], axis=1)
    df_limited = (
        df.groupby(features, as_index=False)
        .head(max_per_combination)
        .reset_index(drop=True)
    )
# old version
    #df_limited = (
        #df.groupby(features, group_keys=False)
        #.apply(lambda x: x.head(max_per_combination))
        #.reset_index(drop=True)
    #)

    X_limited = df_limited[features]
    y_limited = df_limited[target_cols]

    print(f"Original row count: {len(df)}")
    print(f"After limiting: {len(df_limited)} (removed {len(df) - len(df_limited)})")
    print("\nClass distribution after limiting:")
    print(y_limited.value_counts())

    return df_limited


def generate_synthetic_overloaded(df, features, target_col): # used in perform_custom_oversampling
    """
    Generate synthetic overloaded samples to balance classes per node_type.

    Parameters
    ----------
    df : pd.DataFrame
        Input dataset (after limiting).
    features : list
        Feature column names.
    target_col : str
        Binary target column name (0 = non-overloaded, 1 = overloaded).

    Returns
    -------
    df_augmented : pd.DataFrame
        Dataset containing newly generated synthetic rows.
    """
    print("\n=== Generating synthetic overloaded samples (Unique Features Balancing) ===")

    rate_cols = [col for col in df.columns if col.startswith("rate_function_")]
    node_types = df["node_type"].unique()
    augmented_rows = []
    generated_total = 0

    existing_keys = set(tuple(row[col] for col in features) for _, row in df.iterrows())

    for nt in node_types:
        subset = df[df["node_type"] == nt]
        count_1 = subset[subset[target_col] == 1].shape[0]
        count_0 = subset[subset[target_col] == 0].shape[0]
        needed = count_0 - count_1

        print(f"\n[Node Type {nt}] Overloaded: {count_1}, Non-overloaded: {count_0}")
        if needed <= 0:
            print(f"Already balanced or overloaded.")
            continue

        print(f"Generating {needed} synthetic samples for node_type {nt}")
        df_overloaded = subset[subset[target_col] == 1]
        generated = 0

        for _, row in df_overloaded.iterrows():
            overloaded_funcs = [col for col in rate_cols if row[col] > 0]
            if len(overloaded_funcs) != 3:
                continue

            fixed_rates = {col: row[col] for col in overloaded_funcs}

            for target_func in overloaded_funcs:
                start = int(fixed_rates[target_func])
                for val in range(start + 5, 201, 10):
                    if generated >= needed:
                        break

                    new_row = {col: 0.0 for col in rate_cols}
                    for col in overloaded_funcs:
                        new_row[col] = val if col == target_func else fixed_rates[col]

                    # Fill metadata and targets
                    new_row["node_type"] = nt
                    new_row[target_col] = 1

                    # Add other columns from original
                    for col in df.columns:
                        if col not in new_row and col not in rate_cols:
                            new_row[col] = row[col]

                    new_key = tuple(new_row[col] for col in features)
                    if new_key not in existing_keys:
                        augmented_rows.append(new_row)
                        existing_keys.add(new_key)
                        generated += 1
                        generated_total += 1

                if generated >= needed:
                    break
            if generated >= needed:
                break

        print(f"Generated {generated} samples for node_type {nt}")

    print(f"\n Total synthetic samples generated: {generated_total}")
    return pd.DataFrame(augmented_rows)


def balance_df_nodewise(df, df_augmented, node_col='node_type', target_col='overloaded_node'): # used in perform_custom_oversampling
    """
    Balance df within each node_type based on overloaded_node (target).
    df_augmented contains only rows with overloaded_node = 1.
    Includes detailed debug prints.
    """

    balanced_parts = []
    node_types = df[node_col].unique()

    print("\n========= ROWS BALANCING =========\n")
    print(f"Node types found: {list(node_types)}\n")

    for nt in node_types:
        print(f"\n--- Processing node_type: {nt} ---")

        subset = df[df[node_col] == nt].copy()

        # Count original samples
        count_1 = (subset[target_col] == 1).sum()
        count_0 = (subset[target_col] == 0).sum()

        print(f"Original counts → overloaded=0: {count_0}, overloaded=1: {count_1}")

        # Check if balance is needed
        if count_1 >= count_0:
            print("Already balanced or overloaded=1 is majority. No augmentation needed.")
            balanced_parts.append(subset)
            continue

        needed = count_0 - count_1
        print(f"Need to add {needed} more rows for overloaded=1")

        # Filter augmented rows for this node_type
        aug_rows = df_augmented[df_augmented[node_col] == nt]

        if aug_rows.empty:
            print(f"[WARNING] df_augmented has NO rows for node_type={nt}. Cannot balance this group!")
            balanced_parts.append(subset)
            continue

        print(f"Augmented rows available for this node_type={nt}: {len(aug_rows)}")

        # Calculate repeat factor
        repeats = ceil(needed / len(aug_rows))
        print(f"Repeating augmented rows {repeats} times")

        repeated = pd.concat([aug_rows] * repeats, ignore_index=True)

        rows_to_add = repeated.iloc[:needed]
        print(f"Rows actually added: {len(rows_to_add)}")

        # Append augmented rows
        subset = pd.concat([subset, rows_to_add], ignore_index=True)

        # Verify new counts
        new_count_1 = (subset[target_col] == 1).sum()
        new_count_0 = (subset[target_col] == 0).sum()
        print(f"After augmentation → overloaded=0: {new_count_0}, overloaded=1: {new_count_1}")

        balanced_parts.append(subset)

    print("\n========= BALANCING COMPLETED =========\n")
    final_df = pd.concat(balanced_parts, ignore_index=True)
    return final_df


def perform_custom_oversampling(df, features, reg_target, class_target): # used in prepare_feature_target_datasets(not in the notebook) and cross_validate
    """
    Custom domain-aware oversampling replacing SMOTENC.

    Steps:
    1. Limit identical feature combinations.
    2. Generate synthetic overloaded samples per node_type to balance unique features(Group level balance).
    3. Row-level Balance by duplicating augmented rows and returning a balanced dataset.

    Parameters
    ----------
    df : pd.DataFrame
    features : list
        Feature columns used for grouping and synthesis.
    reg_target : list
        Regression Target column(s).
    class_target : list
        Classification Target column(s).

    Returns
    -------
    X_resampled, y_resampled : pd.DataFrame, pd.DataFrame
        Balanced feature and target datasets.
    """
    printmd("## Oversampling")
    # Step 1: Apply limiting rule
    df_class = df[features + class_target]
    df_limited = limit_identical_combinations(df_class, features, class_target)

    # Step 2: Combine for rebalancing
    # df_limited = pd.concat([X_limited, y_limited], axis=1)
    target_col = class_target[0]

    # Step 3: Generate new samples to balance limited dataset
    df_augmented = generate_synthetic_overloaded(df_limited, features, target_col)

    # Optionally save the augmented rows
    os.makedirs(PATH_TO_AUGMENTED_ROWS, exist_ok=True)
    df_augmented.to_csv(PATH_TO_AUGMENTED_ROWS + "augmented_overloaded_samples.csv", index=False)
    print("Augmented rows saved to 'augmented_overloaded_samples.csv'")

    # Step 4: Final overall balance dataset (repeated features)
    df_balanced = balance_df_nodewise(df, df_augmented)
    X_res = df_balanced[features]
    y_res = df_balanced[reg_target + class_target]

    print("\nFinal class distribution after rebalancing:")
    print(y_res[class_target].value_counts())
    print("\nFinal class distribution after rebalancing (node_type-wise):")
    print(df_balanced.groupby("node_type")["overloaded_node"].value_counts().unstack(fill_value=0))

    print("\nFinal node_type distribution:")
    print(X_res["node_type"].value_counts())

    print("\n========= FINAL UNIQUE FEATURES SUMMARY =========")

    # Convert to tuples for unique combinations
    all_unique = df_balanced[features].drop_duplicates()
    unique_0 = df_balanced[df_balanced[target_col] == 0][features].drop_duplicates()
    unique_1 = df_balanced[df_balanced[target_col] == 1][features].drop_duplicates()

    print(f"Total unique feature combinations       : {len(all_unique)}")
    print(f"Unique feature combinations for 0       : {len(unique_0)}")
    print(f"Unique feature combinations for 1       : {len(unique_1)}")

    print("==========================================\n")

    return X_res, y_res, df_augmented, df_balanced

In [68]:
# PREPROCESS_FOLD---------------------------------------------------------------------------------------------------------------
def check_node_type_distribution(X_train, X_val, X_test, node_col='node_type', normalize=True): # used in preprocessing(not used in kan) and preprocess_fold
    """
    Check and compare the distribution of `node_type` (or any categorical feature)
    across train, validation, and test splits.

    Parameters
    ----------
    X_train, X_val, X_test : pd.DataFrame
        DataFrames for training, validation, and test sets.
    node_col : str, default='node_type'
        Name of the column representing node types (or any categorical variable).
    normalize : bool, default=True
        If True, show proportions (%) instead of raw counts.

    Returns
    -------
    pd.DataFrame
        Summary table comparing distributions across splits.
    """
    # Validate column existence
    for split_name, df in zip(['Train', 'Val', 'Test'], [X_train, X_val, X_test]):
        if node_col not in df.columns:
            raise ValueError(f"'{node_col}' not found in {split_name} set.")

    # Compute distributions
    def get_dist(df, name):
        return df[node_col].value_counts(normalize=normalize).rename(name)

    dist_train = get_dist(X_train, 'Train')
    dist_val   = get_dist(X_val, 'Val')
    dist_test  = get_dist(X_test, 'Test')

    # Combine into one comparison DataFrame
    dist_summary = pd.concat([dist_train, dist_val, dist_test], axis=1).fillna(0)
    if normalize:
        dist_summary = dist_summary * 100  # show as %

    # Add total rows for reference
    total_counts = {
        "Train Total": len(X_train),
        "Val Total": len(X_val),
        "Test Total": len(X_test)
    }
    totals_df = pd.DataFrame(total_counts, index=["Total Rows"])

    printmd("## Node Type Distribution Across Splits:")
    print(dist_summary.round(2))
    print("\n Dataset Sizes:")
    print(totals_df)

    return dist_summary



def check_data_leakage(X_train, X_val, X_test, group_cols=None): # used in preprocessing and preprocess_fold
    """
    Verify that there is no data leakage (i.e., no repeated feature combinations)
    across train, validation, and test splits.

    Parameters
    ----------
    X_train, X_val, X_test : pd.DataFrame
        DataFrames for train, validation, and test sets.
    group_cols : list of str, optional
        Columns to consider for checking duplicates.
        If None, all columns of X_train are used.

    Returns
    -------
    None
        Prints leakage report. Raises AssertionError if leakage is detected.
    """


    if group_cols is None:
        group_cols = X_train.columns.tolist()

    # Create a unique signature for each feature combination
    def make_signatures(df):
        return set(df[group_cols].astype(str).agg('-'.join, axis=1))

    sig_train = make_signatures(X_train)
    sig_val   = make_signatures(X_val)
    sig_test  = make_signatures(X_test)

    # Check overlaps
    leak_train_val = sig_train.intersection(sig_val)
    leak_train_test = sig_train.intersection(sig_test)
    leak_val_test = sig_val.intersection(sig_test)

    total_leaks = len(leak_train_val) + len(leak_train_test) + len(leak_val_test)

    printmd("## Data Leakage Check:")

    print(f"Train Samples: {len(X_train)}")
    print(f"Val Samples: {len(X_val)}")
    print(f"Test Samples: {len(X_test)}")

    print("\n")
    # print(f"- Train–Val overlaps: {len(leak_train_val)}")
    # print(f"- Train–Test overlaps: {len(leak_train_test)}")
    # print(f"- Val–Test overlaps: {len(leak_val_test)}")

    if total_leaks == 0:
        print("No data leakage detected. Splits are clean.")
    else:
        print("Data leakage detected!")
        if len(leak_train_val):
            print(f"  → {len(leak_train_val)} overlapping feature groups between Train and Val")
        if len(leak_train_test):
            print(f"  → {len(leak_train_test)} overlapping feature groups between Train and Test")
        if len(leak_val_test):
            print(f"  → {len(leak_val_test)} overlapping feature groups between Val and Test")
        #raise AssertionError("Data leakage detected between splits.")

def fit_minmax_scaler(X, y=None, regression_cols=None, classification_col=None): # used in preprocessing(not used in kan notebook) and preprocess_fold and prepare_cross_domain_evaluation_data(not used in the notebook)
    """
    Fit MinMaxScaler for features (and optionally regression targets).

    X:
      - node_type column is excluded from scaling

    y:
      - only regression columns are scaled
      - classification column remains unchanged
    """

    # ----------------------
    # 1. Handle feature scaler
    # ----------------------
    scaler_x = MinMaxScaler(feature_range=(1, 2))
    # Drop node_type if exists
    if "node_type" in X.columns:
        scaler_x.fit(X.drop(columns=["node_type"]))
    else:
        scaler_x.fit(X)

    # ----------------------
    # 2. Handle target scaler
    # ----------------------
    scaler_y = None
    if y is not None and regression_cols is not None:
        # Fit scaler on regression columns only
        scaler_y = MinMaxScaler(feature_range=(1, 2))
        scaler_y.fit(y[regression_cols])

    # ---- Logging ----
    print("[INFO] MinMaxScaler fitted:")
    print(f"  - Features shape: {X.shape}")
    if y is not None:
        print(f"  - Regression targets shape: {y[regression_cols].shape}")
        print(f"  - Classification column '{classification_col}' excluded from scaling")
    print()

    return scaler_x, scaler_y


def save_scalers(scaler_x, scaler_y, task_name, base_path='./scalers/functions/'): # used in preprocessing(not used in kan notebook) and preprocess_fold and prepare_cross_domain_evaluation_data(not used in the notebook)
    """
    Save fitted scalers for features and targets.

    Parameters
    ----------
    scaler_x : MinMaxScaler
        Fitted feature scaler.
    scaler_y : MinMaxScaler or None
        Fitted target scaler (if any).
    task_name : str
        Name of the task (e.g., 'Multi_Target_regression', 'overloaded_node_classification')
    base_path : str, default='./scalers/functions/'
        Base directory to save scalers.
    """
    # Create directories
    x_dir = os.path.join(base_path, 'scaler_x')
    y_dir = os.path.join(base_path, 'scaler_y')
    os.makedirs(x_dir, exist_ok=True)
    os.makedirs(y_dir, exist_ok=True)

    # Save X scaler
    joblib.dump(scaler_x, os.path.join(x_dir, f"{task_name}_x.joblib"))

    # Save Y scaler (only if provided)
    if scaler_y is not None:
        joblib.dump(scaler_y, os.path.join(y_dir, f"{task_name}_y.joblib"))

    print(f"[INFO] Scalers saved for target '{task_name}'")
    if scaler_y is None:
        print("  - No target scaler (classification or categorical target).")
    print()

def transform_with_scalers( # used in preprocessing and preprocess_fold 
    X_train, X_val, X_test, scaler_x,
    y_train=None, y_val=None, y_test=None,
    scaler_y=None, regression_cols=None, classification_col=None
):
    """
    Transform train/val/test using fitted scalers.

    X:
      - scales all columns except node_type
      - adds node_type back after scaling

    y:
      - scales only regression targets
      - keeps classification target unchanged
    """

    # =========================================
    # 1. Separate node_type from X
    # =========================================
    def split_node_type(df):
        if "node_type" in df.columns:
            node = df["node_type"].values.reshape(-1, 1)
            df_wo = df.drop(columns=["node_type"])
        else:
            node = None
            df_wo = df
        return df_wo, node


    X_train_noNT, node_train = split_node_type(X_train)
    X_val_noNT, node_val = split_node_type(X_val)
    X_test_noNT, node_test = split_node_type(X_test)

    # =========================================
    # 2. Scale numeric features only
    # =========================================
    X_train_scaled = scaler_x.transform(X_train_noNT)
    X_val_scaled   = scaler_x.transform(X_val_noNT)
    X_test_scaled  = scaler_x.transform(X_test_noNT)

    # Add back node_type (not scaled)
    if node_train is not None:
        X_train_scaled = np.hstack([node_train, X_train_scaled])
        X_val_scaled   = np.hstack([node_val, X_val_scaled ])
        X_test_scaled  = np.hstack([node_test, X_test_scaled])

    # =========================================
    # 3. Handle Y scaling
    # =========================================
    if y_train is not None and scaler_y is not None:

        # Extract and scale regression columns
        y_train_reg_s = scaler_y.transform(y_train[regression_cols])
        y_val_reg_s   = scaler_y.transform(y_val[regression_cols])
        y_test_reg_s  = scaler_y.transform(y_test[regression_cols])

        # Recombine regression + classification
        y_train_scaled = pd.DataFrame(y_train_reg_s, columns=regression_cols)
        y_val_scaled   = pd.DataFrame(y_val_reg_s, columns=regression_cols)
        y_test_scaled  = pd.DataFrame(y_test_reg_s, columns=regression_cols)

        # Add classification target unchanged
        y_train_scaled[classification_col] = y_train[classification_col].values
        y_val_scaled[classification_col]   = y_val[classification_col].values
        y_test_scaled[classification_col]  = y_test[classification_col].values

    else:
        y_train_scaled, y_val_scaled, y_test_scaled = y_train, y_val, y_test

    # ---- Logging ----
    print("[INFO] Transformation complete.")
    print(f"  - X_train shape: {X_train_scaled.shape}")
    print(f"  - X_val shape: {X_val_scaled.shape}")
    print(f"  - X_test shape: {X_test_scaled.shape}\n")

    return (
        X_train_scaled, X_val_scaled, X_test_scaled,
        y_train_scaled, y_val_scaled, y_test_scaled
    )

def transform(df, rate_columns=None, pad_value=0.0): # used in preprocessing and preprcess_fold and prepare_cross_domain_evaluation_data(not used in the notebook)
    """
    Transform the input dataframe into padded, variable-length sequences.

    Each sample becomes a sequence of steps where each step = [rate, method_onehot(6), node_type].
    Steps with zero rate are removed. Then sequences are padded to the same length.

    Returns:
        X_padded: np.ndarray, shape (num_samples, max_seq_len, 8)
        mask: np.ndarray, shape (num_samples, max_seq_len), 1 for valid, 0 for padded
    """

    if rate_columns is None:
        rate_columns = [
            'rate_function_env', 'rate_function_curl', 'rate_function_eat_memory',
            'rate_function_nmap', 'rate_function_shasum', 'rate_function_figlet'
        ]

    node_type = df['node_type'].values
    num_samples = df.shape[0]
    sequence_length = len(rate_columns)  # 6

    # One-hot encode method indices (0–5)
    method_ids = np.arange(sequence_length).reshape(-1, 1)
    encoder = OneHotEncoder(sparse_output=False, categories='auto')
    method_onehot = encoder.fit_transform(method_ids)  # (6, 6)

    X_sequences = []

    for i in range(num_samples):
        node_val = node_type[i]
        rate_values = df.loc[i, rate_columns].values  # shape (6,)

        # Keep only non-zero steps
        nonzero_mask = rate_values != 1
        if not np.any(nonzero_mask):
            nonzero_mask = np.array([True])  # Keep one dummy step if all zero

        rate_seq = rate_values[nonzero_mask].reshape(-1, 1)
        method_seq = method_onehot[nonzero_mask]
        node_seq = np.full((np.sum(nonzero_mask), 1), node_val)

        seq = np.concatenate([rate_seq, method_seq, node_seq], axis=1)  # (L_i, 8)
        X_sequences.append(seq)

    # Pad all sequences to same length (post-padding with zeros)
    max_len = max(len(seq) for seq in X_sequences)
    X_padded = pad_sequences(X_sequences, maxlen=max_len, dtype='float32', padding='post', value=pad_value)

    # Create mask (1 for real steps, 0 for padded)
    mask = np.array([[1]*len(seq) + [0]*(max_len - len(seq)) for seq in X_sequences], dtype='float32')

    # Drop node_type column if you want to reuse df
    df = df.drop(columns=['node_type'])

    return X_padded

def preprocess_fold(X_train, X_val, X_test, y_train, y_val, y_test,tasks,base_path): # used in cross_validate
    """
    Perform full preprocessing pipeline:
    - Split data into train/validation/test sets
    - Fit MinMax scalers for features and (optionally) targets
    - Save scalers to disk
    - Transform datasets using fitted scalers
    - Return scaled datasets and scalers for all tasks
    """
    printmd("## Preprocessing")
    # -----------------------------------------------------
    # Initialize dictionaries to store splits and scalers
    # -----------------------------------------------------
    x_train_dict, x_val_dict, x_test_dict = {}, {}, {}
    y_train_dict, y_val_dict, y_test_dict = {}, {}, {}
    x_scalers, y_scalers = {}, {}

    # -----------------------------------------------------
    # Loop through each task for preprocessing
    # -----------------------------------------------------
    for task_name,task_info in tasks.items():
        printmd(f"# {task_name}")
        printmd("---")


        # -------------------------------------------------
        # Check for data leakage
        # -------------------------------------------------
        check_node_type_distribution(X_train,X_val,X_test)
        check_data_leakage(X_train,X_val,X_test)

        # -------------------------------------------------
        # Fit MinMaxScaler
        # Skip target scaling for classification tasks
        # -------------------------------------------------
        printmd("## Scalaing")
        if task_name == "overloaded_node_classification":
            scaler_x, scaler_y = fit_minmax_scaler(X_train)
        else:
            scaler_x, scaler_y = fit_minmax_scaler(X_train, y_train,
                                                   regression_cols=task_info["regression_targets"],
                                                  classification_col=task_info["classification_targets"])

        # -------------------------------------------------
        # Save fitted scalers to disk
        # -------------------------------------------------
        save_scalers(scaler_x, scaler_y, task_name, base_path)

        # -------------------------------------------------
        # Apply scaling to train/val/test sets
        # -------------------------------------------------
        (
            X_train_scaled, X_val_scaled, X_test_scaled,
            y_train_scaled, y_val_scaled, y_test_scaled
        ) = transform_with_scalers(
            X_train, X_val, X_test,
            scaler_x,
            y_train, y_val, y_test,
            scaler_y,
            regression_cols=task_info["regression_targets"],
            classification_col=task_info["classification_targets"]
        )


        # -------------------------------------------------
        # Optional: Apply any custom transformation on scaled features
        # Skip this step for classification tasks
        # -------------------------------------------------
        print(f"Transforming for Janoosy: {datetime.datetime.now()}")
        if task_name != "overloaded_node_classification":
            X_train_scaled = transform(pd.DataFrame(X_train_scaled, columns=features))
            X_val_scaled = transform(pd.DataFrame(X_val_scaled, columns=features))
            X_test_scaled = transform(pd.DataFrame(X_test_scaled, columns=features))

        # -------------------------------------------------
        # Store scaled datasets and scalers in dictionaries
        # -------------------------------------------------
        x_train_dict[task_name] = X_train_scaled
        x_val_dict[task_name] = X_val_scaled
        x_test_dict[task_name] = X_test_scaled
        x_scalers[task_name] = scaler_x

        y_train_dict[task_name] = y_train_scaled
        y_val_dict[task_name] = y_val_scaled
        y_test_dict[task_name] = y_test_scaled
        y_scalers[task_name] = scaler_y

    # -----------------------------------------------------
    # Return all processed splits and scalers
    # -----------------------------------------------------
    return (
        x_train_dict, x_val_dict, x_test_dict, x_scalers,
        y_train_dict, y_val_dict, y_test_dict, y_scalers
    )